"""
Main Entry Point for the RAG (Retrieval-Augmented Generation) Pipeline Demo.

This module provides the command-line interface for the RAG system:
1. Orchestrates the data ingestion phase (loading and embedding documents)
2. Provides an interactive query interface for users
3. Displays answers generated by the RAG pipeline

The flow:
- User runs this script
- PDFs are loaded from the data folder and indexed
- User enters interactive mode to ask questions
- Each question is answered using RAG (retrieval + generation)
"""

from src.rag_pipeline import RAGPipeline


def main():
    """
    Main entry point for the RAG pipeline demonstration.

    This function:
    1. Displays a welcome message
    2. Calls the ingestion pipeline to load and embed documents
    3. Enters an interactive query loop where users can ask questions
    4. Processes each question through the RAG pipeline and displays results

    The interactive loop runs until the user enters 'exit'.
    """
    print("=== RAG Pipeline Demo ===\n")

    # Initialize the RAG pipeline
    pipeline = RAGPipeline()

    # Phase 1: Data Ingestion
    # Load all PDFs from the data folder and create embeddings
    pipeline.ingest()

    # Phase 2: Interactive Query Mode
    print("\n=== Query Mode ===")
    while True:
        # Get user input
        user_query = input("\nAsk a question (or 'exit' to quit): ").strip()

        # Check for exit command
        if user_query.lower() == 'exit':
            break

        print("\nSearching...")
        # Query the RAG pipeline with the user's question
        response = pipeline.query(user_query)

        # Display the generated answer
        print(f"\nAnswer: {response}\n")


if __name__ == "__main__":
    main()
