"""
Main Entry Point for the RAG (Retrieval-Augmented Generation) Pipeline Demo.

This module provides the command-line interface for the RAG system:
1. Orchestrates the data ingestion phase (loading and embedding documents)
2. Provides an interactive query interface for users
3. Displays answers generated by the RAG pipeline

The flow:
- User runs this script
- PDFs are loaded from the data folder and indexed
- User enters interactive mode to ask questions
- Each question is answered using RAG (retrieval + generation)
"""

import sys
import logging
from rag_pipeline import RAGPipeline
from logging_config import setup_logging

# Initialize logging
logger = setup_logging("rag_pipeline_main")


def main() -> None:
    """
    Main entry point for the RAG pipeline demonstration.
    
    Handles:
    - RAG pipeline initialization
    - Data ingestion
    - Interactive query mode
    - Error handling and logging
    """
    try:
        logger.info("=" * 60)
        logger.info("Starting RAG Pipeline Demo")
        logger.info("=" * 60)
        
        print("=== RAG Pipeline Demo ===\n")

        # Initialize pipeline
        try:
            logger.debug("Initializing RAG pipeline...")
            pipeline = RAGPipeline()
            logger.info("RAG pipeline initialized successfully")
        except Exception as e:
            logger.error(f"Failed to initialize RAG pipeline: {type(e).__name__}: {str(e)}", exc_info=True)
            raise

        # Run ingestion
        try:
            logger.info("Starting data ingestion phase...")
            pipeline.ingest()
            logger.info("Data ingestion completed")
        except Exception as e:
            logger.error(f"Ingestion failed: {type(e).__name__}: {str(e)}", exc_info=True)
            print("\nError during data ingestion. Please check the logs for details.")
            sys.exit(1)

        # Query mode
        logger.info("Entering interactive query mode")
        print("\n=== Query Mode ===")
        query_count = 0
        
        while True:
            try:
                # Get user input
                user_query = input("\nAsk a question (or 'exit' to quit): ").strip()
                
                # Check for exit command
                if user_query.lower() == 'exit':
                    logger.info(f"User exited. Processed {query_count} queries.")
                    print("\nGoodbye!")
                    break
                
                if not user_query:
                    logger.debug("Empty query received, skipping")
                    print("Please enter a valid question.")
                    continue
                
                query_count += 1
                logger.info(f"Processing query #{query_count}: {user_query[:100]}")
                
                print("\nSearching...")
                response = pipeline.query(user_query)

                print(f"\nAnswer: {response}\n")
                logger.info(f"Query #{query_count} completed successfully")
                
            except ValueError as e:
                logger.warning(f"Invalid query input: {str(e)}")
                print(f"Error: {str(e)}")
            except FileNotFoundError as e:
                logger.error(f"Required resource not found: {str(e)}", exc_info=True)
                print(f"Error: {str(e)}")
                print("Please ensure data ingestion has been completed successfully.")
                break
            except ConnectionError as e:
                logger.error(f"Connection error: {str(e)}", exc_info=True)
                print("Error: Failed to connect to the language model service.")
                print("Please ensure the LLM service is running.")
                break
            except Exception as e:
                logger.error(f"Unexpected error during query: {type(e).__name__}: {str(e)}", exc_info=True)
                print(f"Error processing query: {str(e)}")
                print("Check the logs for more details.")

        logger.info("=" * 60)
        logger.info("RAG Pipeline Demo Completed")
        logger.info("=" * 60)

    except Exception as e:
        logger.error("=" * 60)
        logger.error(f"CRITICAL ERROR: {type(e).__name__}: {str(e)}", exc_info=True)
        logger.error("=" * 60)
        print("\nCritical error occurred. Please check the logs for details.")
        sys.exit(1)

if __name__ == "__main__":
    main()
