"""
Main Entry Point for the RAG (Retrieval-Augmented Generation) Pipeline Demo.

This module provides the command-line interface for the RAG system:
1. Orchestrates the data ingestion phase (loading and embedding documents)
2. Provides an interactive query interface for users
3. Displays answers generated by the RAG pipeline

The flow:
- User runs this script
- PDFs are loaded from the data folder and indexed
- User enters interactive mode to ask questions
- Each question is answered using RAG (retrieval + generation)
"""

from rag_pipeline import RAGPipeline


def main() -> None:
    """
    Main entry point for the RAG pipeline demonstration.
    """
    print("=== RAG Pipeline Demo ===\n")

    pipeline = RAGPipeline()
    pipeline.ingest()

    print("\n=== Query Mode ===")
    while True:
        # Get user input
        user_query = input("\nAsk a question (or 'exit' to quit): ").strip()
        
        # Check for exit command
        if user_query.lower() == 'exit':
            break
        
        print("\nSearching...")
        response = pipeline.query(user_query)

        print(f"\nAnswer: {response}\n")

if __name__ == "__main__":
    main()
